# IFT patch map (Format 2) header offsets — see https://www.w3.org/TR/IFT/#patch-map-format-2

IFT_ENTRIES_OFFSET_START = 25
IFT_ENTRIES_OFFSET_END = 29
IFT_ENTRY_ID_STRING_OFFSET_START = 29
IFT_ENTRY_ID_STRING_OFFSET_END = 33
IFT_FORMAT_OFFSET = 0
IFT_URL_TEMPLATE_LENGTH_OFFSET = 33
IFT_URL_TEMPLATE_START = 35

IFT_FONT_FILENAME = "myfont-mod.ift.woff2"
