import sys
from pathlib import Path
from typing import List, Dict, Union

# -----------------------
# Import IFTFile from your library
# -----------------------
sys.path.append(str(Path(__file__).resolve().parent.parent))
from testCaseGeneratorLib.iftFile import IFTFile

# -----------------------
# Decode sparse bitset to glyph indices
# -----------------------
def decode_sparse_bitset(data: bytes, base: int = 0) -> List[int]:
    glyphs = []
    for byte_index, byte_val in enumerate(data):
        for bit_index in range(8):
            if byte_val & (1 << (7 - bit_index)):
                glyphs.append(base + byte_index * 8 + bit_index)
    return glyphs

# -----------------------
# Generate filename for entry index
# -----------------------
def generate_filename(entry_index: int, total_tk: int = 20) -> str:
    """
    Produce realistic encoder filenames:
      - Early entries -> _tk files
      - Later entries -> _gk files
    Adjust total_tk based on how many _tk files your encoder generates.
    """
    if entry_index < total_tk:
        return f"{entry_index:02X}.ift_tk"
    else:
        return f"{entry_index - total_tk:02X}.ift_gk"

# -----------------------
# Parse Format 2 IFT table
# -----------------------
def parse_format2_ift_table(ift_data: bytes) -> List[Dict[str, Union[str,int,List[int]]]]:
    offset = 0
    data_len = len(ift_data)
    entries: List[Dict[str, Union[str,int,List[int]]]] = []

    # --- Header ---
    format_byte = ift_data[offset]
    offset += 1
    if format_byte != 2:
        raise ValueError("Only Format 2 supported")
    offset += 3  # reserved
    flags = ift_data[offset]
    offset += 1

    # Skip compatibility ID (16 bytes)
    offset += 16

    default_patch_format = ift_data[offset]
    offset += 1

    # Header URL template (ignored for now, filenames generated by index)
    header_url_len = ift_data[offset]
    offset += 1
    offset += header_url_len  # skip header URL bytes

    # --- Parse entries ---
    entry_index = 0
    while offset < data_len:
        entry_format = ift_data[offset]
        offset += 1

        # Per-entry URL length (ignored)
        url_len = ift_data[offset]
        offset += 1
        offset += url_len

        # Determine patch data until next 0x00 or 0x01
        next_entry_offset = offset
        while next_entry_offset < data_len and ift_data[next_entry_offset] not in (0x00, 0x01):
            next_entry_offset += 1
        patch_data = ift_data[offset:next_entry_offset]
        offset = next_entry_offset

        # Decode glyphs
        glyphs = decode_sparse_bitset(patch_data) if entry_format == 1 else list(range(len(patch_data)))

        # Generate realistic filename
        url = generate_filename(entry_index)

        entry = {
            "entryFormat": entry_format,
            "url": url,
            "patchFormat": default_patch_format,
            "glyphs": glyphs,
            "patchBytes": patch_data.hex()
        }
        entries.append(entry)
        entry_index += 1

    return entries

# -----------------------
# Load IFT table
# -----------------------
iftFile = IFTFile("exampleTestFile", "GLYF", "myfont-mod.ift.woff2")
ift_data = iftFile.getIFTTableData()

patch_entries = parse_format2_ift_table(ift_data)

# -----------------------
# Print entries
# -----------------------
for idx, e in enumerate(patch_entries):
    print(f"Entry {idx}:")
    print("  url:", e["url"])
    print("  patchFormat:", e["patchFormat"])
    print("  glyphs:", e["glyphs"])
    print()
